### ISSUE TITLE
Bluetooth RF Comm Chat does not work

### ISSUE THREAD

**Issue by pierresa** [Microsoft/Windows-universal-samples#178]
downloaded on 2 windows10 PCs (paired with Bluetooth). Deployed on 2 machines. On one stared froegroud listener.OK. On the other started chat client. Message: no chat service found (in red)

(same if I do the opposite combination)

what do I need to do?

**Comment by ArmsOfSorrow** [comment]
I'm facing the same issue, with a notebook on one side and Lumia 520 with Windows 10 Insider Preview on the other one. Advertising/enumerating does not throw exceptions on any device, but they still can't see each other. I paired them before starting the sample, but they don't

**Comment by Sohra** [comment]
Same behaviour, using Lumia 930 (build 10536.1004) and Surface Pro 3 (10240 RTM)

**Comment by GauravC12** [comment]
Same here. Lumia 630 and Envy 6

**Comment by pellski** [comment]
Using an Inspiron 15 7537 and Lumia 640XL, having exactly the same problems. Has anyone succeeded with this application?

**Comment by pellski** [comment]
FIX (for my issue anyway):
Step 1 - Make sure Bluetooth drivers are up to date
Step 2 - Make sure your PC/Laptop name can be seen (use bluetooth settings)
Step 3 - Pair your phone to your laptop via bluetooth
The app should now work

**Comment by Sohra** [comment]
I have latest updates on RTM desktop, and the latest on my Lumia 930 (but build 10536.1004, not the newer 10549 that was just released), and the October Update 2 commit.

My devices are paired and desktop settings app shows my phone as a connected device, but my devices still can't connect in this app in any combination of device and scenario.  I notice if I connect to a paired device from the phone side, after showing as "connected", a few seconds later it reverts to "paired" again, and the bluetooth icon disappears from the notification bar, and action center icon shows "not connected" despite the desktop still listing it under connected devices.  Not sure if 10549 fixes that or whether it has anything to do with the inability of this app to connect.

**Comment by pierresa** [comment]
No it does not. Sorry it juts does not work. (by the way I am pairing 2 laptops under windows 10 (no phone))

**Comment by Sohra** [comment]
I repeated my tests using 10549 on my 930 device, behaviour is unchanged from what was previously reported.

**Comment by ArmsOfSorrow** [comment]
Quick update: it gets better. I'm currently using build 10581 and the phone can find my laptop. The reverse doesn't work, though, if I run the server on the phone, the laptop can't see it.

Can somebody test it using 2 phones? I can't do that myself yet, as Win10 is not available for my Samsung ATIV S yet.

**Comment by ArmsOfSorrow** [comment]
Just tested with 10586.11 mobile build and it doesn't work any more. Neither the laptop running 10240 nor the desktop PC running 10586.3 can see the phone and vice versa.

Could you please fix this, Microsoft? Non-functional "universal" APIs defeat the whole purpose of deploying the same app to multiple device categories if they don't work across devices (and make my app pretty much useless, btw).

Fyi, I'm using a CSL Bluetooth Nano Stick with generic Microsoft drivers (because Bluetooth settings disappear in the W10 control panel and the app crashes on starting the client/server when I install the manufacturer's older Windows drivers) on the PC side and a Nokia Lumia 520 running the above mentioned W10 mobile build.

**Comment by Sohra** [comment]
I have 10586.11 installed on four devices, Lumia 735, 930, Surface Pro 3, and HP Envy 14.  Although these devices can pair with each other, they will not remain connected - after connection they immediately disconnect - and of course the sample can't work if they are not currently connected.  Seems like the OS still can't connect two devices running Windows 10, even though it can maintain a connection to a bluetooth mouse and surface pen without trouble.

**Comment by ArmsOfSorrow** [comment]
I think that's actually expected behavior. The OS doesn't see a need for a persistent connection between devices because no application is using it. If you opened a socket between to paired devices within your app, it'd say "connected" again.

**Comment by Sohra** [comment]
Really?  Can you connect the client to a server with this sample app?  I can't, client always reports no server found, I can only assume that's because they are not actually connected via bluetooth.

**Comment by ArmsOfSorrow** [comment]
Not anymore since upgrading my laptop to build 10586.14.

Seriously Microsoft, could you please get your shit together? This is getting tiresome.
I hope the new VS and SDK update on 30th Nov. is going to make it work at least as it was before.

**Comment by kpathakota** [comment]
Hi folks, sorry for the problems here.  I'll improve the documentation in the main sample.  Here's how to get the sample to work:

Here are the steps to get the server working on Phone:
1. Launch the app
2. Select "Background Server" - it has to be the Background scenario because the only time the phone is discoverable is on the Settings page.  When you navigate to the settings page, it suspends the foreground server (this limitation is removed in Win10 anniversary update so check that sample out in the "dev" branch).  
3. Navigate to the settings page
4. Pair the phone w/ your Client device
5. Run the Chat client
6. Find your phone and start communicating.  

Hope that works!  Let me know if you have any more issues.
